global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'nsenti-dashboard'
    static_configs:
      - targets: ['dashboard:9095']

  - job_name: 'nsenti-workers'
    static_configs:
      - targets: ['address_worker:9092', 'body_worker:9093', 'verification_worker:9096']
        labels:
          group: 'workers'

  - job_name: 'nsenti-scheduler'
    static_configs:
      - targets: ['scheduler:9094']
