global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'nsenti-dashboard'
    static_configs:
      - targets: ['localhost:9095']

  - job_name: 'nsenti-workers'
    static_configs:
      - targets: ['localhost:9092', 'localhost:9093']
        labels:
          group: 'workers'

  - job_name: 'nsenti-scheduler'
    static_configs:
      - targets: ['localhost:9094']
